### DISCUSSION TITLE
Docker Compose Example

### DISCUSSION THREAD

**Discussion by JohnMacrae** [celsworth/lxp-bridge#215] [General]
The contents of the docker compose example (https://github.com/celsworth/lxp-bridge/wiki/docker-compose.yaml.example) seem more like the config.yaml. Is there another version available please?

**Comment by celsworth** [comment]
Hm yes think someone might have had a fat finger edit of that, I'll fix it up :)

But there's an actual example file in the repo at https://github.com/celsworth/lxp-bridge/blob/master/docker-compose.yaml.example

**Comment by JohnMacrae** [comment]
You're right - thank you :)

(I'm an idiot)

**Comment by JohnMacrae** [comment]
FWIW, I store my config files in /opt/lxp-bridge/config.yaml. I've been unable to map source and target to allow lxp-bridge to run under docker compose. When run manually, it starts just fine from the /opt/lxp-bridge directory. Any hints much appreciated.

**Comment by celsworth** [comment]
I think it should just be this?

```
   volumes:
   - type: bind
     source: /opt/lxp-bridge/config.yaml
     target: /etc/config.yaml
```

All we're doing is telling Docker to make the file that's at `/opt/lxp-bridge/config.yaml` in the host, and make it available at `/etc/config.yaml` in the container (this is just where lxp-bridge looks for its config by default, which is a pretty bad default but thats another story).

If that's not working you'll have to give more details, what's the error? Is lxp-bridge not able to read it?

**Comment by JohnMacrae** [comment]
Yes - that's exactly what I had set up but consistently get the error: 2023-10-26T16:53:22.760124409Z Error: error reading /etc/config.yaml: No such file or directory (os error 2)

Weird.

My Compose file:
```
  lxp-bridge:
    container_name: lxp-bridge
    image: celsworth/lxp-bridge:latest
    restart: unless-stopped
    init: true
    volumes:
      - type: bind
        source: /opt/lxp-bridge/config.yaml
        target: /etc/config.yaml
```

**Comment by celsworth** [comment]
Hm I can't reproduce this. If I have a config file at that path and use this docker-compose, it works:

```
version: '3.4'

services:
 lxp-bridge:
   container_name: lxp-bridge
   image: celsworth/lxp-bridge:latest
   restart: unless-stopped
   init: true
   volumes:
     - type: bind
       source: /opt/lxp-bridge/config.yaml
       target: /etc/config.yaml
```

Since I'm running it on Docker Desktop for Mac I did have to add /opt to the list of allowed filepaths in the Preferences, but other than that its fine..

btw: enclose things in three backticks (code block) to keep formatting.
