### DISCUSSION TITLE
Home Assistant - Show and Tell - Your integrations and cards

### DISCUSSION THREAD

**Discussion by jacovt** [celsworth/lxp-bridge#247] [General]
Hello everyone,

Starting this to just get some community feedback (and hopefully some ideas) about how you are using the lxp-bridge Home Assistant integration. It would be nice to see your integrations, dashboards, automation and other interesting things you do with your inverters using the HA integration provided by lxp-bridge.

If you could maybe include references to any custom cards and other 3rd party integration you use, that would be very useful.

Thank you!
---Jaco

**Comment by andrewfraley** [comment]
I've put together something really basic, will update this if I add more.  Just do a search and replace with your dongle id, eg replace `REPLACEME` with `lxp_dj12345678`

![image](https://github.com/user-attachments/assets/bdf12997-6bd9-4adc-84d2-0238a460f9d4)



```
views:
  - title: 12000xp
    type: sections
    max_columns: 4
    icon: mdi:solar-power
    sections:
      - type: grid
        cards:
          - graph: line
            type: sensor
            detail: 2
            entity: sensor.REPLACEME_battery_voltage
            name: Battery Voltage
            grid_options:
              columns: 6
              rows: 2
          - graph: line
            type: sensor
            detail: 2
            entity: sensor.REPLACEME_state_of_charge
            name: State of Charge
          - type: gauge
            entity: sensor.REPLACEME_battery_discharge
            max: 12800
            severity:
              green: 0
              yellow: 7680
              red: 10240
            name: Battery Discharging
            needle: true
            grid_options:
              columns: 6
              rows: 3
            min: 0
          - type: gauge
            entity: sensor.REPLACEME_battery_charge
            max: 5120
            severity:
              green: 0
              yellow: 3072
              red: 4096
            name: Battery Charging
            needle: true
            grid_options:
              columns: 6
              rows: 3
          - type: gauge
            entity: sensor.REPLACEME_inverter_power
            max: 18000
            severity:
              green: 0
              yellow: 12000
              red: 15000
            name: Inverter Power
            needle: true
            grid_options:
              columns: 6
              rows: 3
          - type: gauge
            entity: sensor.REPLACEME_ac_charge_power
            max: 5120
            severity:
              green: 0
              yellow: 3072
              red: 4096
            needle: true
            name: AC Charge Power
            grid_options:
              columns: 6
              rows: 3
          - type: gauge
            entity: sensor.REPLACEME_power_from_grid
            max: 18000
            severity:
              green: 0
              yellow: 12000
              red: 15000
            name: Power From Grid
            needle: true
            grid_options:
              columns: 6
              rows: 3
          - type: gauge
            entity: sensor.REPLACEME_pv_power_array
            severity:
              green: 0
              yellow: 20000
              red: 24000
            name: Power From PV
            needle: true
            grid_options:
              columns: 6
              rows: 3
            max: 28000
            min: 0
          - type: entities
            entities:
              - entity: sensor.REPLACEME_fault_code
                name: Fault Code
                secondary_info: none
              - entity: sensor.REPLACEME_warning_code
                name: Warning Code
              - entity: sensor.REPLACEME_status
                name: Status
            title: Inverter Status
          - type: heading
            heading_style: title
      - type: grid
        cards:
          - type: entities
            entities:
              - entity: sensor.REPLACEME_battery_charge_today
                name: Battery Charge (Today)
              - entity: sensor.REPLACEME_battery_discharge_today
                name: Battery Discharge (Today)
              - entity: sensor.REPLACEME_battery_charge_all_time
                name: Battery Charge (All time)
              - entity: sensor.REPLACEME_battery_discharge_all_time
                name: Battery Discharge (All time)
            title: Battery
          - type: entities
            entities:
              - entity: sensor.REPLACEME_pv_power_array
                name: PV Power (Array)
              - entity: sensor.REPLACEME_pv_power_string_1
                name: PV Power (String 1)
              - entity: sensor.REPLACEME_pv_power_string_2
                name: PV Power (String 2)
              - entity: sensor.REPLACEME_pv_generation_today
                name: PV Generation (Today)
              - entity: sensor.REPLACEME_pv_generation_all_time
                name: PV Generation (All time)
            title: PV
          - type: entities
            entities:
              - entity: sensor.REPLACEME_radiator_1_temperature
                name: Radiator 1 Temperature
              - entity: sensor.REPLACEME_radiator_2_temperature
                name: Radiator 2 Temperatur
            state_color: true
            title: Inverter Temps
      - type: grid
        cards: []


```
