### ISSUE TITLE
Add more frequent requesting of input data

### ISSUE THREAD

**Issue by celsworth** [celsworth/lxp-bridge#113]
Expanding from discussions in #103, it's becoming clear that it would be nice to get input data a lot more frequently than the 5 minutes the inverter sends it out automatically.

This isn't a massive job but there a few technicalities that might make this a bit tricky than at first glance.

The mobile app requests data every 10 seconds in Local Connect mode, so we'll emulate this essentially. In order to not create a new data row on the Luxpower portal every 10 seconds, I believe only registers 0-79 (ie not 80-119) are requested by the app, so we'll do the same.

This creates a problem that the MQTT packet `lxp/{datalog}/inputs/all`, and database rows, and InfluxDB, are all only populated when we get those registers 80-119 (aka `inputs/3`). So we need a way to tell all these subprocesses that data is not arriving, and if we want to fill in the various databases, we need a value to put in those columns. MQTT could just use nulls, InfluxDB can be omitted, but the database columns are NOT NULL; perhaps it would be better to use the most recent `inputs/3` data, as those don't change very often.

**Comment by Beenay25** [comment]
I might be misinterpreting what you're asking, but the following automation worked for me : 

```
alias: Poll Battery State 1 & 2
trigger:
  - platform: time_pattern
    seconds: /15
action:
  - service: mqtt.publish
    data:
      topic: lxp/cmd/<YOUR INVERTER ID>/read/inputs/1
      retain: true
  - service: mqtt.publish
    data:
      topic: lxp/cmd/<YOUR INVERTER ID>/read/inputs/2
      retain: true
mode: single

```

Replace `<YOUR INVERTER ID>` with the inverter's internal SSID (browse to the inverter's IP and look under **AP Mode Settings**)

It'll send out a MQTT request to the router every 15 seconds and gets a response sent out.
