### ISSUE TITLE
Noob Question : My values on Home assistant are showing as Unknown

### ISSUE THREAD

**Issue by muhammadqasimc** [celsworth/lxp-bridge#150]
Hi all, im fairly new to this whole Home assistant thing

![Screenshot from 2023-03-20 21-20-55](https://user-images.githubusercontent.com/42121445/226445318-0adbad23-e21d-4806-a1a1-31bb7528b198.png)

I followed the documentation fairly well but as you can see my entities are showing as unknown

Any help will be highly appreciated

In my case the inverter Ip is 192.168.10.137 and the port is 8182

my MQTT broker has the standard port 1883
and the home assistant ip is 192.168.10.105

I think its also worth noting that i dont require having control of the inverter. All i need is monitoring

Here is my current config.yaml code
After modifying it i do restart the lxp-bridge.

```
inverters:
- enabled: true
  host: 192.168.10.137
  port: 8182
  serial: 9999999999
  datalog: 2222222223
  heartbeats: false
- enabled: false
  host: 192.168.0.163
  port: 8000
  serial: 9999999999
  datalog: 3333333333
  heartbeats: false

databases:
- enabled: false
  url: postgres://lxp:lxp@localhost/lxp
  url: mysql://lxp:lxp@localhost/lxp
  url: sqlite://lxp.db

mqtt:
  enabled: true
  host: 192.168.10.105
  port: 1883
  username: my username here
  password: my password here
  namespace: lxp
  homeassistant:
    enabled: true
    prefix: homeassistant

influx:
  enabled: false
  url: http://localhost:8086
  username:
  password:
  database: lxp

scheduler:
  enabled: false
  timesync:
    enabled: false
    cron: "0 0 * * *
```
`
