### ISSUE TITLE
Home Assistant: error loading config

### ISSUE THREAD

**Issue by dbainbridge** [celsworth/lxp-bridge#225]
Just installed fresh copy of HA and also added lxp-bridge but get this error when trying to start it up.  Also note the log level is listed as INFO even though I have the config set as TRACE.

```
[20:24:31] INFO: Creating lxp-bridge config from options...
Done.
[20:24:31] INFO: Starting lxp-bridge...
Error: inverters[0]:  must be exactly 10 characters at line 3 column 5
```

```
loglevel: trace
inverters:
  - enabled: true
    host: 192.168.20.223
    port: 8000
    serial: ""
    datalog: ""
    heartbeats: false
    publish_holdings_on_connect: false
databases:
  - enabled: false
    url: postgres://lxp:lxp@localhost/lxp
mqtt:
  enabled: true
  host: localhost
  port: 1883
  username: ""
  password: ""
  namespace: lxp
influx:
  enabled: false
  url: http://localhost:8086
  username: ""
  password: ""
  database: lxp

```
