### ISSUE TITLE
Sample docker-compose.yml

### ISSUE THREAD

**Issue by IMgoRt** [celsworth/lxp-bridge#52]
Hi Chris,
For those of us who prefer a docker-compose.yml, the following replicates your command:

```
version: '3.4'

services:
  lxp-bridge:
    container_name: lxp-bridge:latest
    image: celsworth/lxp-bridge
    restart: unless-stopped
    init: true
    volumes:
    - type: bind
      source: ${PWD}/config.yaml
      target: /etc/config.yaml 
```
